### ISSUE TITLE
List all loaded modules

### ISSUE THREAD

**Issue by phoe** [ruricolist/vernacular#3]
How should I retrieve a list of all modules currently loaded into Vernacular? The best I have found is `find-module` that nonetheless requires a pathname to be specified.

**Comment by phoe** [comment]
I see that `vernacular/importing::*claimed-module-names*` contains a hash table containing names of all loaded modules along with their import paths. Is it possible to export this information in any way?

**Comment by ruricolist** [comment]
The idea with `*claimed-module-names*` is to prevent a module name from being accidentally re-defined; it wasn't intended as a catalog.

I'm not averse to the idea, but let me ask: what do you need a listing of modules for?

**Comment by phoe** [comment]
I would like to retrieve a list all exported symbols per file loaded by CL-YESQL for introspection purposes. For that, I figured that I'd need a list of modules, unless I also keep that list myself in my own code.

**Comment by phoe** [comment]
```lisp
(defun loaded-modules-alist ()
  "Return an alist of (path . module-object) for all loaded modules."
  (loop for path being the hash-keys of *module-cells*
          using (hash-value cell)
        unless (eql never (module-cell.timestamp cell))
          collect (cons path (module-cell.module cell))))
```

What is `never`? I assume it is a slot, but I do not see `with-slots` being used here.

**Comment by ruricolist** [comment]
It's a constant, part of Overlord's implementation of timestamps. Basically
the negative infinity of timestamps.

**Comment by ruricolist** [comment]
Implemented in https://github.com/ruricolist/overlord/blob/master/stamp.lisp.
