### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by phoe** [ruricolist/vernacular#5]
I hate to just be a person that makes ten GitHub issues in a row on your repositories and there, that's all folks.

Do you have any kind of LiberaPay, Patreon or any other PayPal where I can throw some tips at you for supporting your Lisp libraries?

**Comment by ruricolist** [comment]
I didn't, but what the hell, I do now. It would be nice to be able to justify spending time implementing new features, not just reacting to GitHub issues.

https://www.paypal.me/ruricolist
https://liberapay.com/ruricolist
https://www.patreon.com/ruricolist

**Comment by phoe** [comment]
Perfect! As soon as my money trickles in, I'll throw something at you. Thanks!

I suggest adding them to http://ruricolist.com/ before closing this issue.

**Comment by ruricolist** [comment]
Done. Thanks for the push and the contribution.
