### ISSUE TITLE
Package lock with serapeum issue

### ISSUE THREAD

**Issue by quicklisp** [ruricolist/vernacular#8]
I'm getting a new failure recently:

`Unhandled SB-EXT:SYMBOL-PACKAGE-LOCKED-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A30083}>: Lock on package SERAPEUM violated when defining DROP-PREFIX as a function while in package VERNACULAR/IMPORT-SET.`

**Comment by ruricolist** [comment]
This should be fixed now.
